In [22]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/competitions/digit-recognizer/sample_submission.csv
/kaggle/input/competitions/digit-recognizer/train.csv
/kaggle/input/competitions/digit-recognizer/test.csv

In [23]:
df=pd.read_csv('/kaggle/input/competitions/digit-recognizer/train.csv')

In [24]:
df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=2)

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [27]:
clf1=LogisticRegression()
clf2=DecisionTreeClassifier()

In [28]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [29]:
y_pred1=clf1.predict(X_test)
y_pred2=clf2.predict(X_test)

In [30]:
from sklearn.metrics import accuracy_score,confusion_matrix
print('logisticRegression accuracy_score',accuracy_score(y_test,y_pred1))
print('decision Tree classifier',accuracy_score(y_test,y_pred2))

logisticRegression accuracy_score 0.9145238095238095
decision Tree classifier 0.8501190476190477

In [31]:
print(' logisticRegression confusion_matrix \n')
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,10)))

 logisticRegression confusion_matrix

     0    1    2    3    4    5    6    7    8    9
0  750    0   13    7    6   20    9    1    9    6
1    0  897   11    8   10    3    7    5   20    1
2   14   15  664   29   12   20   18   28   23    6
3    9   12   29  686    7   40   12   17   31   21
4    5    4   13    7  724   14    9    7   23   50
5   14   10   14   41    6  577   18   11   25   13
6   11    1    9    7   13   19  758    0   16    5
7    5   11   26   12    6    6    1  781    6   19
8    8   13   29   32   17   28   16    7  618   25
9    7    3    8   18   46   16    5   21   24  686

In [32]:
print('Desicion Tree Classifier confusion matrix/n')
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,10)))

Desicion Tree Classifier confusion matrix/n

     0    1    2    3    4    5    6    7    8    9
0  750    0   13    7    6   20    9    1    9    6
1    0  897   11    8   10    3    7    5   20    1
2   14   15  664   29   12   20   18   28   23    6
3    9   12   29  686    7   40   12   17   31   21
4    5    4   13    7  724   14    9    7   23   50
5   14   10   14   41    6  577   18   11   25   13
6   11    1    9    7   13   19  758    0   16    5
7    5   11   26   12    6    6    1  781    6   19
8    8   13   29   32   17   28   16    7  618   25
9    7    3    8   18   46   16    5   21   24  686

In [34]:
from sklearn.metrics import precision_score,recall_score,f1_score

<h1><b>Average have two hidden pairamite(avg=weighted,None,macro)

In [36]:
precision_score(y_test,y_pred1,average='weighted')

0.9142150713630827

In [39]:
recall_score(y_test,y_pred1,average='weighted')

0.9145238095238095

In [40]:
f1_score(y_test,y_pred1,average='weighted')

0.9142794994052751

In [43]:
from sklearn.metrics import classification_report
print('classsification_report matrix',classification_report(y_test,y_pred1))

classsification_report matrix               precision    recall  f1-score   support

           0       0.95      0.96      0.96       821
           1       0.95      0.98      0.96       962
           2       0.91      0.90      0.91       829
           3       0.90      0.88      0.89       864
           4       0.93      0.94      0.94       856
           5       0.87      0.84      0.85       729
           6       0.93      0.94      0.94       839
           7       0.91      0.93      0.92       873
           8       0.86      0.88      0.87       793
           9       0.89      0.88      0.89       834

    accuracy                           0.91      8400
   macro avg       0.91      0.91      0.91      8400
weighted avg       0.91      0.91      0.91      8400