In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/saurabh00007/iriscsv/Iris.csv

In [3]:
df=pd.read_csv('/kaggle/input/datasets/saurabh00007/iriscsv/Iris.csv')

In [4]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
df['Species']=encoder.fit_transform(df['Species'])

In [7]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=1)

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [13]:
clf1=LogisticRegression()
clf2=DecisionTreeClassifier()

In [15]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [16]:
y_pred1=clf1.predict(X_test)
y_pred2=clf2.predict(X_test)

In [17]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [19]:
print('accuracy_score in logisticRegression',accuracy_score(y_test,y_pred1))
print('accuracy_score in decision_tree',accuracy_score(y_test,y_pred2))

accuracy_score in logisticRegression 1.0
accuracy_score in decision_tree 0.9666666666666667

In [20]:
print('confusion matrix in logisticRegression /n')
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,3)))

confusion matrix in logisticRegression /n

    0   1  2
0  11   0  0
1   0  13  0
2   0   0  6

In [21]:
print('confusion matrix in DecisiontreeClassifier /n')
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,3)))

confusion matrix in DecisiontreeClassifier /n

    0   1  2
0  11   0  0
1   0  12  1
2   0   0  6

In [22]:
result=pd.DataFrame()
result['Actual Result']=y_test
result['LogisticRegression prediction']=y_pred1
result['decisiomnTreeClassifier prerdiction']= y_pred2
result.sample(10)

,Actual Result,LogisticRegression prediction,decisiomnTreeClassifier prerdiction
40,0,0,0
73,1,1,1
146,2,2,2
66,1,1,1
92,1,1,1
75,1,1,1
5,0,0,0
16,0,0,0
125,2,2,2
77,1,1,1

In [25]:
from sklearn.metrics import precision_score,recall_score
precision_score(y_test,y_pred1,average=None)

array([1., 1., 1.])

In [26]:
recall_score(y_test,y_pred1,average=None)

array([1., 1., 1.])