In [1]:
import numpy as np
import pandas as pd

In [2]:
date=pd.read_csv('orders.csv')
time=pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

<h1></b>Working with date <b></h1>

In [53]:
date['date']=pd.to_datetime(date['date'])

In [54]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             1000 non-null   datetime64[ns]
 1   date_year        1000 non-null   int32
 2   date_month_name  1000 non-null   object
 3   date_of now      1000 non-null   int32
 4   date_day         1000 non-null   object
 5   week day name    1000 non-null   object
 6   wekend           1000 non-null   int64
dtypes: datetime64[ns](1), int32(2), int64(1), object(3)
memory usage: 47.0+ KB

<h2>Extract the year</h2>

In [8]:
date['date_year']=date['date'].dt.year

In [9]:
date.sample(5)

          date  product_id  city_id  orders  date_year
927 2018-12-04         219        3       3       2018
989 2019-02-20         438       22      28       2019
277 2018-11-21        2017       11       3       2018
187 2019-05-29         586       28       2       2019
239 2019-02-19        4823       18      26       2019

<h2>Extract the month</h2>

In [10]:
date['date_month_name'] = date['date'].dt.month_name()

date.head()

        date  product_id  city_id  orders  date_year date_month_name
0 2019-12-10        5628       25       3       2019        December
1 2018-08-15        3646       14     157       2018          August
2 2018-10-23        1859       25       1       2018         October
3 2019-08-17        7292       25       1       2019          August
4 2019-01-06        4344       25       3       2019         January

<h2>Extract the day_num</h2>

In [13]:
date['date_day']=date['date'].dt.day

In [14]:
date.sample(5)

          date  product_id  city_id  orders  date_year  dae_month  date_day
197 2018-09-14        3440       26     101       2018          9        14
905 2018-08-22         133       16       2       2018          8        22
141 2018-12-17        1640       26       1       2018         12        17
61  2018-07-20        7025       14      22       2018          7        20
388 2019-01-19        4075       18      25       2019          1        19

<h2>Extract the day</h2>

In [15]:
date['date_day']=date['date'].dt.day_name()

In [16]:
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_name,date_of now,date_day
525,2019-06-13,2249,20,2,2019,June,3,Thursday
74,2019-11-13,2199,14,2,2019,November,2,Wednesday
192,2019-04-21,21,24,3,2019,April,6,Sunday
519,2019-11-01,6377,14,4,2019,November,4,Friday
560,2018-08-04,358,10,15,2018,August,5,Saturday

<h2>Extract the day_of_week</h2>

In [21]:
date['date_of now']=date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month_name,date_of now,date_day,week day name
0,2019-12-10,5628,25,3,2019,December,1,Tuesday,Tuesday
1,2018-08-15,3646,14,157,2018,August,2,Wednesday,Wednesday
2,2018-10-23,1859,25,1,2018,October,1,Tuesday,Tuesday
3,2019-08-17,7292,25,1,2019,August,5,Saturday,Saturday
4,2019-01-06,4344,25,3,2019,January,6,Sunday,Sunday

In [25]:
date['week day name']=date['date'].dt.day_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month_name,date_of now,date_day,week day name
0,2019-12-10,5628,25,3,2019,December,1,Tuesday,Tuesday
1,2018-08-15,3646,14,157,2018,August,2,Wednesday,Wednesday
2,2018-10-23,1859,25,1,2018,October,1,Tuesday,Tuesday
3,2019-08-17,7292,25,1,2019,August,5,Saturday,Saturday
4,2019-01-06,4344,25,3,2019,January,6,Sunday,Sunday

In [28]:
date=date.drop(columns=['product_id','city_id','orders'])

In [29]:
date.head()

        date  date_year date_month_name  date_of now   date_day week day name
0 2019-12-10       2019        December            1    Tuesday       Tuesday
1 2018-08-15       2018          August            2  Wednesday     Wednesday
2 2018-10-23       2018         October            1    Tuesday       Tuesday
3 2019-08-17       2019          August            5   Saturday      Saturday
4 2019-01-06       2019         January            6     Sunday        Sunday

<h2>Extract the _weekend</h2>

In [42]:
date['wekend']=np.where(date['date_day'].isin(['Sunday','Saturday']),1,0)

In [48]:
date.sample(5)

,date,date_year,date_month_name,date_of now,date_day,week day name,wekend
788,2018-11-03,2018,November,5,Saturday,Saturday,1
339,2019-12-05,2019,December,3,Thursday,Thursday,0
319,2018-07-10,2018,July,1,Tuesday,Tuesday,0
756,2018-08-30,2018,August,3,Thursday,Thursday,0
358,2019-01-19,2019,January,5,Saturday,Saturday,1

<h2>Extract the _week_num</h2>

In [59]:
date['date_week'] = date['date'].dt.isocalendar().week

date.head()

,date,date_year,date_month_name,date_of now,date_day,week day name,wekend,date_week
0,2019-12-10,2019,December,1,Tuesday,Tuesday,0,50
1,2018-08-15,2018,August,2,Wednesday,Wednesday,0,33
2,2018-10-23,2018,October,1,Tuesday,Tuesday,0,43
3,2019-08-17,2019,August,5,Saturday,Saturday,1,33
4,2019-01-06,2019,January,6,Sunday,Sunday,1,1

<h2>Extract the quarter</h2>

In [60]:
date['quarter'] = date['date'].dt.quarter
date.head()

,date,date_year,date_month_name,date_of now,date_day,week day name,wekend,date_week,quarter
0,2019-12-10,2019,December,1,Tuesday,Tuesday,0,50,4
1,2018-08-15,2018,August,2,Wednesday,Wednesday,0,33,3
2,2018-10-23,2018,October,1,Tuesday,Tuesday,0,43,4
3,2019-08-17,2019,August,5,Saturday,Saturday,1,33,3
4,2019-01-06,2019,January,6,Sunday,Sunday,1,1,1

<h2>Extract the semster</h2>

In [61]:
date['semester']=np.where(date['quarter'].isin([1,2]),1,2)
date.head()

,date,date_year,date_month_name,date_of now,date_day,week day name,wekend,date_week,quarter,semester
0,2019-12-10,2019,December,1,Tuesday,Tuesday,0,50,4,2
1,2018-08-15,2018,August,2,Wednesday,Wednesday,0,33,3,2
2,2018-10-23,2018,October,1,Tuesday,Tuesday,0,43,4,2
3,2019-08-17,2019,August,5,Saturday,Saturday,1,33,3,2
4,2019-01-06,2019,January,6,Sunday,Sunday,1,1,1,1

In [62]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 8, 17, 19, 2, 7, 591050)

In [63]:
today - date['date']

0     2442 days 19:02:07.591050
1     2924 days 19:02:07.591050
2     2855 days 19:02:07.591050
3     2557 days 19:02:07.591050
4     2780 days 19:02:07.591050
                 ...
995   2870 days 19:02:07.591050
996   2811 days 19:02:07.591050
997   2659 days 19:02:07.591050
998   2724 days 19:02:07.591050
999   2498 days 19:02:07.591050
Name: date, Length: 1000, dtype: timedelta64[ns]

In [64]:

(today - date['date']).dt.days

0      2442
1      2924
2      2855
3      2557
4      2780
       ...
995    2870
996    2811
997    2659
998    2724
999    2498
Name: date, Length: 1000, dtype: int64

In [67]:
# Months passed

np.round((today -date['date']) / np.timedelta64(1, 'm'),0)

0      3517622.0
1      4211702.0
2      4112342.0
3      3683222.0
4      4004342.0
         ...
995    4133942.0
996    4048982.0
997    3830102.0
998    3923702.0
999    3598262.0
Name: date, Length: 1000, dtype: float64

<h1>Working with time</h1>

In [68]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [70]:
time['date']=pd.to_datetime(time['date'])

In [71]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [72]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

<h2>Extract the time </h2>

In [73]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

<h3>Extract the time </h3>

In [74]:
today - time['date']

0     4628 days 18:12:07.591050
1     4492 days 19:22:07.591050
2     4978 days 18:41:07.591050
3     4280 days 18:31:07.591050
4     4677 days 19:51:07.591050
                 ...
995   5267 days 18:12:07.591050
996   4588 days 19:48:07.591050
997   5053 days 19:25:07.591050
998   5169 days 19:28:07.591050
999   4441 days 19:37:07.591050
Name: date, Length: 1000, dtype: timedelta64[ns]

In [75]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.999247e+08
1      3.881785e+08
2      4.301665e+08
3      3.698587e+08
4      4.041643e+08
           ...
995    4.551343e+08
996    3.964745e+08
997    4.366491e+08
998    4.466717e+08
999    3.837730e+08
Name: date, Length: 1000, dtype: float64

In [76]:
# in month

(today - time['date'])/np.timedelta64(1,'m')

0      6.665412e+06
1      6.469642e+06
2      7.169441e+06
3      6.164311e+06
4      6.736071e+06
           ...
995    7.585572e+06
996    6.607908e+06
997    7.277485e+06
998    7.444528e+06
999    6.396217e+06
Name: date, Length: 1000, dtype: float64

In [77]:
# in hour

(today - time['date'])/np.timedelta64(1,'h')

0      111090.202109
1      107827.368775
2      119490.685442
3      102738.518775
4      112267.852109
           ...
995    126426.202109
996    110131.802109
997    121291.418775
998    124075.468775
999    106603.618775
Name: date, Length: 1000, dtype: float64