In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import numpy as np

In [6]:
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'} 
webpage=requests.get('https://www.ambitionbox.com/list-of-companies?page=1',headers=headers).text

In [8]:
soup=BeautifulSoup(webpage,'lxml')

In [ ]:
#print(soup.prettify())

In [14]:
soup.find_all("h1")[0].get_text(" ", strip=True)

'Top Companies in INDIA'

In [16]:
len(soup.find_all('h2'))

24


TO FIND OUT NAMES OF THE COMPANIES

In [40]:
cards = soup.find_all("div", class_="companyCardWrapper")

for card in cards:
    company = card.find("h2").text.strip()
    print(company)

TCS
Accenture
Wipro
Cognizant
Capgemini
HDFC Bank
Infosys
HCLTech
ICICI Bank
Tech Mahindra
Genpact
TP
Axis Bank
Jio
Concentrix Corporation
Amazon
Reliance Retail
iEnergizer
LTM Limited
HDB Financial Services

TO FIND OUT THE RATINGS

In [ ]:
cards = soup.find_all("div", class_="companyCardWrapper")

for card in cards:
    rating = card.find("div", class_="rating_text")
    if rating:
        print(rating.text.strip())

In [45]:
company = soup.find_all("h2")
ratings = soup.find_all("div", class_="rating_text")

print("Companies:", len(company))
print("Ratings:", len(ratings))

Companies: 24
Ratings: 20

In [25]:
cards = soup.find_all("div", class_="companyCardWrapper")

for card in cards:
    company = card.find("h2").text.strip()

    rating = card.find("div", class_="rating_text")

    if rating:
        print(company, ":", rating.text.strip())
    else:
        print(company, ": Rating Not Found")

TCS : 3.3
Accenture : 3.7
Wipro : 3.6
Cognizant : 3.7
Capgemini : 3.6
HDFC Bank : 3.8
Infosys : 3.5
HCLTech : 3.4
ICICI Bank : 4.0
Tech Mahindra : 3.3
Genpact : 3.6
TP : 3.9
Axis Bank : 3.6
Jio : 4.4
Concentrix Corporation : 3.5
Amazon : 3.9
Reliance Retail : 3.9
iEnergizer : 4.5
LTM Limited : 3.6
HDB Financial Services : 3.9


TO FIND OUT THE NUMBER OF REVIEWS

In [46]:
cards = soup.find_all("div", class_="companyCardWrapper")

for card in cards:
    review = card.find("span", class_="companyCardWrapper__companyRatingCount")
    if review:
        print(review.text.strip())

(1.2L)
(75.8k)
(66.8k)
(63.1k)
(55.2k)
(54.4k)
(50.2k)
(47.4k)
(47k)
(44.6k)
(43.8k)
(40k)
(34.4k)
(34.2k)
(33.1k)
(32.6k)
(28k)
(27.8k)
(27.3k)
(26.5k)

In [51]:
for card in cards:
    info = card.find("span", class_="companyCardWrapper__interLinking")
    if info:
        print(info.text.strip().split("|")[0].strip())

IT Services & Consulting
IT Services & Consulting
IT Services & Consulting
IT Services & Consulting
IT Services & Consulting
Banking
IT Services & Consulting
IT Services & Consulting
Banking
IT Services & Consulting
Analytics & KPO
BPO
Banking
Telecom
BPO
Internet
Retail
BPO
IT Services & Consulting
NBFC

In [52]:
for card in cards:
    info = card.find("span", class_="companyCardWrapper__interLinking")
    if info:
        print(info.text.strip().split("|")[1].strip())

Bengaluru +476 other locations
Bengaluru +279 other locations
Hyderabad +390 other locations
Hyderabad +252 other locations
Bengaluru +204 other locations
Mumbai +1894 other locations
Bengaluru +257 other locations
Chennai +248 other locations
Mumbai +1470 other locations
Hyderabad +338 other locations
Hyderabad +186 other locations
Mumbai +266 other locations
Mumbai +1561 other locations
Mumbai +1980 other locations
Bengaluru +193 other locations
Bengaluru +553 other locations
Mumbai +1179 other locations
Noida +55 other locations
Bengaluru +154 other locations
Mumbai +1113 other locations

In [54]:
salary = []
interview = []
jobs = []

cards = soup.find_all("div", class_="companyCardWrapper")

for card in cards:
    counts = card.find_all("span", class_="companyCardWrapper__ActionCount")

    if len(counts) >= 4:
        salary.append(counts[1].text.strip())
        interview.append(counts[2].text.strip())
        jobs.append(counts[3].text.strip())

print("Salary:", salary)
print("Interview:", interview)
print("Jobs:", jobs)

Salary: ['10.4L', '7.3L', '4.9L', '6.1L', '5L', '1.5L', '5.3L', '4L', '1.6L', '2.9L', '2.4L', '1L', '1L', '61.1k', '1.3L', '1.6L', '74.7k', '25.1k', '2L', '49.2k']
Interview: ['11.4k', '9.5k', '7k', '6.6k', '5.7k', '3.2k', '8.6k', '4.6k', '3k', '4.7k', '4k', '2.3k', '2k', '4.5k', '2k', '6.1k', '2k', '1.7k', '3.5k', '1.1k']
Jobs: ['5k', '19.9k', '104', '973', '2.3k', '458', '3.1k', '284', '18', '670', '513', '1.8k', '210', '--', '12', '70', '92', '60', '957', '2']

In [57]:
final = pd.DataFrame()

headers = {
    "User-Agent": "Mozilla/5.0"
}

for j in range(1, 101):

    url = f"https://www.ambitionbox.com/list-of-companies?page={j}"

    webpage = requests.get(url, headers=headers).text

    soup = BeautifulSoup(webpage, "lxml")

    cards = soup.find_all("div", class_="companyCardWrapper")

    company = []
    rating = []
    reviews = []
    company_type = []
    head_office = []
    salaries = []
    interviews = []
    jobs = []

    for card in cards:

        # Company Name
        try:
            company.append(card.find("h2").text.strip())
        except:
            company.append(np.nan)

        # Rating
        try:
            rating.append(card.find("div", class_="rating_text").text.strip())
        except:
            rating.append(np.nan)

        # Reviews
        try:
            reviews.append(card.find("span", class_="companyCardWrapper__companyRatingCount").text.strip())
        except:
            reviews.append(np.nan)

        # Company Type & Head Office
        try:
            info = card.find("span", class_="companyCardWrapper__interLinking").text.strip()
            company_type.append(info.split("|")[0].strip())
            head_office.append(info.split("|")[1].strip())
        except:
            company_type.append(np.nan)
            head_office.append(np.nan)

        # Salaries, Interviews, Jobs
        try:
            counts = card.find_all("span", class_="companyCardWrapper__ActionCount")
            salaries.append(counts[1].text.strip())
            interviews.append(counts[2].text.strip())
            jobs.append(counts[3].text.strip())
        except:
            salaries.append(np.nan)
            interviews.append(np.nan)
            jobs.append(np.nan)

    df = pd.DataFrame({
        "Company": company,
        "Rating": rating,
        "Reviews": reviews,
        "Company_Type": company_type,
        "Head_Office": head_office,
        "Salaries": salaries,
        "Interviews": interviews,
        "Jobs": jobs
    })

    final = pd.concat([final, df], ignore_index=True)

print(final.shape)

ValueError: All arrays must be of the same length

In [58]:
print(len(company))
print(len(rating))
print(len(reviews))
print(len(company_type))
print(len(head_office))
print(len(salaries))
print(len(interviews))
print(len(jobs))

20
20
20
21
20
20
20
20

In [66]:
final = pd.DataFrame()

for page in range(1, 101):

    url = f"https://www.ambitionbox.com/list-of-companies?page={page}"
    webpage = requests.get(url, headers=headers).text

    soup = BeautifulSoup(webpage, "lxml")

    cards = soup.find_all("div", class_="companyCardWrapper")

    company = []
    reviews = []
    company_type = []
    head_office = []
    salaries = []
    interviews = []
    jobs = []

    for card in cards:

        # Company Name
        try:
            company.append(card.find("h2").text.strip())
        except:
            company.append(np.nan)

        # Rating
        

        # Reviews
        try:
            reviews.append(card.find("span", class_="companyCardWrapper__companyRatingCount").text.strip())
        except:
            reviews.append(np.nan)

        # Company Type & Head Office
        try:
            info = card.find("span", class_="companyCardWrapper__interLinking").text.strip()
            parts = [x.strip() for x in info.split("|")]

            company_type.append(parts[0] if len(parts) > 0 else np.nan)
            head_office.append(parts[1] if len(parts) > 1 else np.nan)

        except:
            company_type.append(np.nan)
            head_office.append(np.nan)

        # Salaries, Interviews, Jobs
        try:
            counts = card.find_all("span", class_="companyCardWrapper__ActionCount")

            salaries.append(counts[1].text.strip() if len(counts) > 1 else np.nan)
            interviews.append(counts[2].text.strip() if len(counts) > 2 else np.nan)
            jobs.append(counts[3].text.strip() if len(counts) > 3 else np.nan)

        except:
            salaries.append(np.nan)
            interviews.append(np.nan)
            jobs.append(np.nan)

    df = pd.DataFrame({
        "Company": company,
        
        "Reviews": reviews,
        "Company_Type": company_type,
        "Head_Office": head_office,
        "Salaries": salaries,
        "Interviews": interviews,
        "Jobs": jobs
    })

    final = pd.concat([final, df], ignore_index=True)

print(final.shape)
final.head()

(2000, 7)

,Company,Reviews,Company_Type,Head_Office,Salaries,Interviews,Jobs
0,TCS,(1.2L),IT Services & Consulting,Bengaluru +476 other locations,10.4L,11.4k,5k
1,Accenture,(75.8k),IT Services & Consulting,Bengaluru +279 other locations,7.3L,9.5k,19.9k
2,Wipro,(66.8k),IT Services & Consulting,Hyderabad +390 other locations,4.9L,7k,104
3,Cognizant,(63.1k),IT Services & Consulting,Hyderabad +252 other locations,6.1L,6.6k,973
4,Capgemini,(55.2k),IT Services & Consulting,Bengaluru +204 other locations,5L,5.7k,2.3k

In [68]:
final

,Company,Reviews,Company_Type,Head_Office,Salaries,Interviews,Jobs
0,TCS,(1.2L),IT Services & Consulting,Bengaluru +476 other locations,10.4L,11.4k,5k
1,Accenture,(75.8k),IT Services & Consulting,Bengaluru +279 other locations,7.3L,9.5k,19.9k
2,Wipro,(66.8k),IT Services & Consulting,Hyderabad +390 other locations,4.9L,7k,104
3,Cognizant,(63.1k),IT Services & Consulting,Hyderabad +252 other locations,6.1L,6.6k,973
4,Capgemini,(55.2k),IT Services & Consulting,Bengaluru +204 other locations,5L,5.7k,2.3k
...,...,...,...,...,...,...,...
1995,Innovatiview India Ltd,(568),Emerging Technologies,Noida +16 other locations,1.4k,82,25
1996,RAK Ceramics,(568),Building Material,Mumbai +66 other locations,1.8k,36,14
1997,Brigade Group,(570),Real Estate,Bengaluru +13 other locations,2.8k,46,133
1998,Micromax Informatics,(567),Consumer Electronics & Appliances,New Delhi +118 other locations,1.3k,23,--
1999,Regalix,(567),Marketing & Advertising,Hyderabad +9 other locations,2.9k,59,59

In [69]:
final.to_csv("companies.csv", index=False)

In [70]:
df = pd.read_csv("companies.csv")
df.head()

,Company,Reviews,Company_Type,Head_Office,Salaries,Interviews,Jobs
0,TCS,(1.2L),IT Services & Consulting,Bengaluru +476 other locations,10.4L,11.4k,5k
1,Accenture,(75.8k),IT Services & Consulting,Bengaluru +279 other locations,7.3L,9.5k,19.9k
2,Wipro,(66.8k),IT Services & Consulting,Hyderabad +390 other locations,4.9L,7k,104
3,Cognizant,(63.1k),IT Services & Consulting,Hyderabad +252 other locations,6.1L,6.6k,973
4,Capgemini,(55.2k),IT Services & Consulting,Bengaluru +204 other locations,5L,5.7k,2.3k